# Generated by Django 4.2 on 2023-04-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlassType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("prenom", models.CharField(blank=True, max_length=150, null=True)),
                ("phone", models.CharField(blank=True, max_length=150, null=True)),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("doctor", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de Création"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de dernière mise à jour"
                    ),
                ),
                (
                    "type_de_verre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.glasstype",
                        verbose_name=" Type de verre",
                    ),
                ),
            ],
        ),
    ]
