# Generated by Django 4.2 on 2023-04-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_menture"),
    ]

    operations = [
        migrations.AddField(
            model_name="menture",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
