# Generated by Django 4.2 on 2023-04-05 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_menture_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="menture",
            name="progressif",
            field=models.CharField(
                blank=True,
                choices=[("PRES", "PRES"), ("LOIN", "LOIN")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PhotoClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.ImageField(upload_to="images/clients")),
                ("actif", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="core.client",
                    ),
                ),
            ],
        ),
    ]
