# Generated by Django 4.2 on 2023-04-05 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_achat_lentiltype_remove_menture_client_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achat",
            name="actif",
        ),
        migrations.AddField(
            model_name="achat",
            name="paid",
            field=models.BooleanField(default=True, verbose_name="paid"),
        ),
        migrations.AlterField(
            model_name="achat",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achats",
                to="core.client",
            ),
        ),
    ]
