# Generated by Django 4.2 on 2023-04-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_achat_actif_achat_paid_alter_achat_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achat",
            old_name="totale",
            new_name="total",
        ),
        migrations.AlterField(
            model_name="lentil",
            name="eye_choice",
            field=models.CharField(
                choices=[("OD", "OD"), ("OG", "OG")], max_length=2, verbose_name="OEUIL"
            ),
        ),
        migrations.AlterField(
            model_name="menture",
            name="eye_choice",
            field=models.CharField(
                choices=[("OD", "OD"), ("OG", "OG")], max_length=2, verbose_name="OEUIL"
            ),
        ),
        migrations.AlterField(
            model_name="progressif",
            name="eye_choice",
            field=models.CharField(
                choices=[("OD", "OD"), ("OG", "OG")], max_length=2, verbose_name="OEUIL"
            ),
        ),
    ]
