# Generated by Django 4.2 on 2023-04-05 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_rename_achat_order_rename_achat_lentil_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="type_de_verre",
        ),
        migrations.AddField(
            model_name="order",
            name="type_de_verre",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.glasstype",
                verbose_name=" Type de verre",
            ),
            preserve_default=False,
        ),
    ]
