# Generated by Django 4.2 on 2023-04-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_client_type_de_verre_order_type_de_verre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="core.client",
            ),
        ),
    ]
