# Generated by Django 4.2 on 2023-04-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_menture"),
    ]

    operations = [
        migrations.AddField(
            model_name="menture",
            name="price",
            field=models.DecimalField(
                decimal_places=0, default=1, max_digits=10, verbose_name="Prix"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menture",
            name="name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Désignation"
            ),
        ),
    ]
