# Generated by Django 4.2 on 2023-04-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_menture_price_alter_menture_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressif",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
