# Generated by Django 4.2 on 2023-04-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_progressif_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ordonnance_return",
            field=models.BooleanField(default=False, verbose_name="Ordonnance rendue"),
        ),
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Payé"),
        ),
        migrations.AlterField(
            model_name="progressif",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de Traitement"
            ),
        ),
    ]
