# Generated by Django 4.2 on 2023-04-05 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_glass_vision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progressif",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.order",
                verbose_name="progressifs",
            ),
        ),
    ]
