# Generated by Django 4.2 on 2023-04-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_glassdeloin_order_alter_glassdepres_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="emergency",
            field=models.BooleanField(default=False, verbose_name="Commande urgente"),
        ),
    ]
