# Generated by Django 4.2 on 2023-04-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_lentil_axe_alter_progressif_progressif"),
    ]

    operations = [
        migrations.AddField(
            model_name="glassdeloin",
            name="addition",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Addition"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="glassdepres",
            name="addition",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=10, verbose_name="Addition"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lentil",
            name="axe",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="progressif",
            name="addition",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Addition"
            ),
        ),
    ]
