# Generated by Django 4.2 on 2023-04-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_glassdepres_addition"),
    ]

    operations = [
        migrations.AddField(
            model_name="progressif",
            name="type_de_verre",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.glasstype",
                verbose_name=" Type de verre",
            ),
            preserve_default=False,
        ),
    ]
