# Generated by Django 4.2 on 2023-04-06 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_progressifdeloin_progressifdepres_delete_progressif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progressifdeloin",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="de_loin_progressifs",
                to="core.order",
            ),
        ),
        migrations.AlterField(
            model_name="progressifdepres",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="de_pres_progressifs",
                to="core.order",
            ),
        ),
    ]
