# Generated by Django 4.2 on 2023-04-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_progressifdeloin_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progressifdepres",
            name="addition",
        ),
        migrations.RemoveField(
            model_name="progressifdepres",
            name="date",
        ),
    ]
