# Generated by Django 4.2 on 2023-04-06 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_remove_progressifdepres_addition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progressifdepres",
            name="type_de_verre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.glasstype",
                verbose_name=" Type de verre",
            ),
        ),
    ]
