# Generated by Django 4.2 on 2023-04-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_progressifdepres_type_de_verre"),
    ]

    operations = [
        migrations.AddField(
            model_name="glassdeloin",
            name="spheric_glass",
            field=models.BooleanField(default=False, verbose_name="Verre Spherique"),
        ),
        migrations.AddField(
            model_name="glassdepres",
            name="spheric_glass",
            field=models.BooleanField(default=False, verbose_name="Verre Spherique"),
        ),
        migrations.AddField(
            model_name="lentil",
            name="spheric_glass",
            field=models.BooleanField(default=False, verbose_name="Verre Spherique"),
        ),
        migrations.AddField(
            model_name="progressifdeloin",
            name="spheric_glass",
            field=models.BooleanField(default=False, verbose_name="Verre Spherique"),
        ),
        migrations.AddField(
            model_name="progressifdepres",
            name="spheric_glass",
            field=models.BooleanField(default=False, verbose_name="Verre Spherique"),
        ),
    ]
