# Generated by Django 4.2 on 2023-04-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_glassdeloin_spheric_glass_glassdepres_spheric_glass_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lentil",
            name="spheric_glass",
            field=models.BooleanField(default=False, verbose_name="Lentille Spherique"),
        ),
    ]
