# Generated by Django 4.2 on 2023-04-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_lentil_spheric_glass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lentil",
            name="brand",
            field=models.CharField(default=1, max_length=150, verbose_name="Marque"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lentil",
            name="diametre",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="lentil",
            name="rayon",
            field=models.IntegerField(),
        ),
    ]
