# Generated by Django 4.2 on 2023-04-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_glassdeloin_addition"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
