# Generated by Django 4.2 on 2023-04-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glassdeloin",
            name="axe",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="glassdepres",
            name="axe",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="lentil",
            name="axe",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="rest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="versement",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="progressifdeloin",
            name="axe",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="progressifdepres",
            name="axe",
            field=models.IntegerField(),
        ),
    ]
