# Generated by Django 4.2 on 2023-04-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_alter_glassdeloin_axe_alter_glassdepres_axe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
