# Generated by Django 4.2 on 2023-04-15 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_alter_order_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleSummary",
            fields=[],
            options={
                "verbose_name": "Sale Summary",
                "verbose_name_plural": "Sales Summary",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.order",),
        ),
        migrations.AlterField(
            model_name="glassdepres",
            name="type_de_verre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="depres_types_glass",
                to="core.glasstype",
                verbose_name=" Type de verre",
            ),
        ),
    ]
