# Generated by Django 4.2 on 2023-04-18 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_salesummary_alter_glassdepres_type_de_verre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="glasstype",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="salesummary",
            options={
                "verbose_name": "Verres du Jour",
                "verbose_name_plural": "Verres du Jour",
            },
        ),
        migrations.AlterField(
            model_name="glassdeloin",
            name="type_de_verre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deloin_types_glass",
                to="core.glasstype",
                verbose_name=" Type de verre",
            ),
        ),
        migrations.AlterField(
            model_name="progressifdeloin",
            name="type_de_verre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progressif_deloin_types_glass",
                to="core.glasstype",
                verbose_name=" Type de verre",
            ),
        ),
        migrations.AlterField(
            model_name="progressifdepres",
            name="type_de_verre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progressif_depres_types_glass",
                to="core.glasstype",
                verbose_name=" Type de verre",
            ),
        ),
    ]
