# Generated by Django 4.2 on 2023-04-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_alter_glasstype_options_alter_salesummary_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glassdeloin",
            name="axe",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="glassdepres",
            name="axe",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lentil",
            name="axe",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="progressifdeloin",
            name="axe",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="progressifdepres",
            name="axe",
            field=models.IntegerField(default=0),
        ),
    ]
