# Generated by Django 4.2 on 2023-05-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_alter_glassdeloin_axe_alter_glassdepres_axe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BouiraSaleSummary",
            fields=[],
            options={
                "verbose_name": "Verres du Jour AB",
                "verbose_name_plural": "Verres du Jour AB",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.order",),
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Commande"},
        ),
    ]
