# Generated by Django 4.2 on 2023-04-07 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Magasin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nom du magasin"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="numéro de téléphone du magasin",
                    ),
                ),
            ],
        ),
    ]
