# Generated by Django 4.2 on 2023-04-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_magasin"),
    ]

    operations = [
        migrations.AddField(
            model_name="magasin",
            name="adress",
            field=models.CharField(blank=True, max_length=150, verbose_name="Adresse"),
        ),
    ]
