# Generated by Django 4.2 on 2023-04-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_magasin_adress"),
    ]

    operations = [
        migrations.AddField(
            model_name="magasin",
            name="principale",
            field=models.BooleanField(default=False, verbose_name="Magasin principale"),
        ),
    ]
